version = 0.1
[default.deploy.parameters]
stack_name = "ok"
resolve_s3 = true
s3_prefix = "ok"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "S3BucketName=\"ok1\""
